### ISSUE TITLE
Avolites and Pioneer Bridge App Intergration

### ISSUE THREAD

**Issue by InfamousUK** [Deep-Symmetry/beat-link-trigger#101]
After doing some research, Avolites have introduced a new feature in their software that allows the user to connect to Pioneer decks and use the bpm and audio information to manipulate the lighting console/software.

The app that joins the two is called Pioneer Bridge, the problem with this app is that it only allows specific Pioneer PRO DJ LINK products to work.

- CDJ-TOUR1
- DJM-TOUR1
- CDJ-2000NXS2
- DJM-900NXS2

The app works by reading Rekordbox and then passing the information on from there. Would it be possible to introduce a MITM (Man In The Middle) feature where Beat Link Trigger could trick Rekordbox. For example, I own Pioneer XDJ 700 decks, they have link capability but they are not detected in the Pioneer Pro DJ LINK app. Could beatlink trigger sit in the middle and make Rekordbox think that they are CDJ2000NXS instead? 

All I want is the ability to send the BPM from the decks to the Avolites Titan Software. I think it could be a powerful tool having the ability to control Ableton, Avolites and other Bridge enabled apps.

**Comment by Swiftb0y** [comment]
It seems like avolites titan has a webapi: https://www.avolites.com/webapi

You could probably use that to talk directly to titan with with a couple of custom trigger functions.

**Comment by brunchboy** [comment]
Yes, that would be the way to approach it. I was working with a show producer in the US and sent him some sample code. Please give me more details about the specific API you want to use, and I can help you write the code. No changes are required to Beat Link Trigger to perform this kind of integration, that’s the whole point: You can add new code in the field.

**Comment by brunchboy** [comment]
(As to the question of trying to pose as a player with more capabilities and relay traffic, that is not going to be reliable or practical. Even if someone was willing and able to do the massive reverse-engineering required, everyone who wanted to do that would have to set up separate networks for the real and simulated players, which would require additional hardware, cabling, and complexity of configuration.)

**Comment by InfamousUK** [comment]
Unfortunately at the moment I am not using an Avolites Console, I am using the Titan One. The webAPI is not available for the Titan One. 

However, hopefully soon I can get back behind a console. Unfortunately I don't understand what you mean regarding the specific API that I want to use. Do you mean the WebAPI? (Even though I can't access a console at the moment, a tool like this would be very useful). I do apologise for how useless I am with this sort of stuff.

**Comment by brunchboy** [comment]
No apologies necessary! If the webAPI is not available, then I don’t know if we’ll be able to do any sort of integration. I’m sorry that the low-level nature of the DJ Link protocol precludes the kind of “pose in the middle” approach you had in mind; much of it is packets that are broadcast to a hard-coded port number on the entire local network, so as I alluded to above the only way to interpose something would be to use separate networks and cabling. That would be a ton of work and would probably have undesirable latency characteristics even if someone could get it working. It’s not a direction my libraries and projects lend themselves to going.

If the Bridge protocol were public and open, I’d explore whether it could be worked with in other ways, but my little experience with investigating it showed it was closed, licenses were ludicrously expensive (thus ruling out unfunded free projects like mine), and some of the parties involved were extremely hostile and jealously guarding their monopoly in the market.

Does the Titan One support other sorts of tempo sync, such as Ableton Link? Is there documentation for it?

**Comment by brunchboy** [comment]
(And once you do have access to the console, I would be entirely happy to try to help you integrate with its web API. I can look over the documentation for that and send some proposed triggers or shows for you to try out. The person I had been working with before got busy with other things, and I never heard back whether he got it working properly.)

**Comment by InfamousUK** [comment]
Unfortunately the Titan One version of the software prevents users from the ability to timecode, receive audio or anything like that. 

Honestly, that would be a big help. I have been using beatlink trigger for so long, I started using it when it was MAC only. It's the reason as to why I have a MAC. 

If something could be done when I can send both Pioneer Link and Ableton Link to the Avolites Software it would help me alot. 

I am more than happy to do inform you once I get behind a console again. Is there something else I can contact you on? Or would you rather keep communication on here?

**Comment by brunchboy** [comment]
Yes, I just found and skimmed the Titan manual version 11, and found it quite disappointing. There are some MIDI triggers that could be used directly from BLT, but none of them support tempo. There is a “DJ Tap” feature they added for another piece of gear, which would do exactly what we want, but they kept it closed and secret, rather than making an open endpoint that any of us could use, so someone would have to set up a working configuration and take network captures while it was running if we were going to figure out how to use that. I would not hold my breath, alas. So I will close this issue for now, and look forward to hearing from you when we can try with a console. At that time, you can either open another issue, or post a question on the [Gitter channel](https://gitter.im/brunchboy/beat-link-trigger) which is a more informal way to reach more of the active user community. (You can also email me directly as james at deepsymmetry.org which I spelled out in a feeble effort to fend off the more simpleminded spam bots)—but that reaches only me, while Gitter reaches me as well as other people who might have useful ideas or related experience.

Cheers, and thanks for letting me know you’ve been getting use out of BLT!

**Comment by brunchboy** [comment]
Oh, if you have connections with anyone at Avolites, perhaps they could be persuaded to tell us how to use DJ Tap if you explain the situation? But again I would not hold my breath. 😄

**Comment by InfamousUK** [comment]
I'll see what I can do. Also Version 13 is the most recent version of the software, that's what the consoles I'll be using are currently running.
