### ISSUE TITLE
Need to support six real players for CDJ-3000

### ISSUE THREAD

**Issue by brunchboy** [Deep-Symmetry/beat-link-trigger#111]
Once https://github.com/Deep-Symmetry/beat-link/issues/46 has progressed enough, there are changes that need to be made in BLT as well, off the top of my head to the Player Status and Carabiner Connection windows to accommodate six, rather than just four, real players. Hopefully @daffron will be willing to help test these fixes as well.

**Comment by brunchboy** [comment]
@daffron, if you are able to attach logs showing what happens today when a player numbered 5 or 6 is seen on the network, that could help me find some of the places that need fixing.

**Comment by daffron** [comment]
Hey @brunchboy  The bug actually occurs before actually needing those players. I.e the player status did not work until I ticked use a real player.

Im guessing thats due to the way this uses player 5

So the current system works up until 3 players. ( I have two cdj3000s now, with two more in the next week arriving)

**Comment by brunchboy** [comment]
That doesn’t make sense to me, so it is definitely going to require seeing some log files with detailed descriptions of what you are trying and the results you are seeing to get to the bottom of this. Perhaps even WireShark captures, but hopefully it won’t come to that.

**Comment by daffron** [comment]
Hey,

So that seems to be fine today for some reason.

Anyway to create some logs I turned it all on and connect as player 1 & 3 and all worked fine.

I then disconnected, set one play to be player 5 and reconnected

![image](https://user-images.githubusercontent.com/24515104/96387560-7d36ad00-11ff-11eb-8a4b-b8f86f26949f.png)

You can see the trigger list is actually showing player 5 fine, just not appearing in player status


[blt_logs1603060318941-4031063130.zip](https://github.com/Deep-Symmetry/beat-link-trigger/files/5398293/blt_logs1603060318941-4031063130.zip)

**Comment by brunchboy** [comment]
Ah! Thank you for the clarification. Yes, Beat Link Trigger only tries to display players 1 through 4 in player status, because that is all that was possible before. This is a known thing that will need to be updated, and we will need to think about what the layout should be for a six-player window, it will get pretty tall if we keep two players per row, but for most people that would still be nicest.

**Comment by brunchboy** [comment]
Thank you also for the logs. One thing I will want to fix quickly in Beat Link is to only warn once about the unknown packet type `0x0b` because that fills up the logs quickly and makes it hard to find other things. Also, interesting from the logs: of course the channels-on-air packet is going to be longer now as there are more channels. I will need a Wireshark capture from you to help figure that one out as you take channels 5 and 6 on and off the air. What mixer are you using?

**Comment by daffron** [comment]
Hey,

Ill need to look up what Wireshark is. :)

Im using a DJM-V10, which is on the LAN

**Comment by brunchboy** [comment]
That is what I guessed! It’s the first mixer I know of to support that many Pro DJ Link channels. There is no hurry on the Wireshark captures, I have lots of things to work on already, but thank you so much for helping us figure out how to support this hardware. 😄

**Comment by brunchboy** [comment]
Yes, all those lines about the unexpected `0x0b` packets drowned out the logs, and probably caused us to miss some useful information detected when BLT first started. I’ll let you know when there is an updated snapshot build that suppresses the extra ones, so we can capture some more useful logs.

**Comment by daffron** [comment]
Sweet, no problem!

**Comment by brunchboy** [comment]
All right, that took a lot later than I hoped (needed to sign a new contract at Apple, then ran into some troubles with broken external links in the user guide, and deprecated commands in the GitHub Actions that build the release artifacts), but the latest snapshot build should now avoid filling up the log files with endless copies of the same warnings about unrecognized ports and packet types. Let me know if that seems to work, @daffron and when you have a chance to learn a little Wireshark and figure out the longer channels-on-air packets.

**Comment by daffron** [comment]
Thanks,

The next two CDJ's are due to arrive in the next day or so, so will try get some more logs once they are connected also

**Comment by brunchboy** [comment]
Ok, @daffron I have just pushed some enhancements which should enable the Player Status window to work nicely with up to six players. I still need to fix the Carabiner Connection window, but if you could see how Player Status is working when you have a chance, I would appreciate it. (You will need to download the latest [preview release](https://github.com/Deep-Symmetry/beat-link-trigger/releases/tag/v0.7.0-SNAPSHOT) to test it.

**Comment by brunchboy** [comment]
And it turns out the Carabiner window was written in a nice, modular way, so it was easy for me to add support for players 5 and 6 here too. At this point, I hope everything might work properly with six players, but I have to wait for someone to try it for real, and report back. Hopefully there will be plenty of time before your show to shake out any details I forgot!

**Comment by daffron** [comment]
thanks!

I only have 4 x cdj3000 here, but should work the same if I make the
numbers 3,4,5,6 right?

**Comment by brunchboy** [comment]
That would help test the support for the larger channel numbers, and so is worth doing, but you’re not going to know if everything works with six players until you actually try it with six players. So if that is important for your show, be sure to really try it long enough before your show so there is time to fix things and test again until it works, before your show.

**Comment by brunchboy** [comment]
Also, it is important to make sure that all the features you plan to rely on during the show are tested thoroughly in the environment that will exist for the show.

**Comment by daffron** [comment]
Oh thats awesome man!

I guess this will also mean multiple computers can link in if theres only 4
decks?

**Comment by brunchboy** [comment]
I don’t understand what you’re saying about multiple computers here? The protocol has always supported choosing between multiple rekordbox (and rekordbox mobile) computers on the same network, but never getting tracks from more than one at the same time. But none of that is relevant to Beat Link or Beat Link Trigger.

Even with older players, I have been able to run more than one copy of Beat Link Trigger at the same time on different computers (I have only tried two), but at some point it will exhaust networking and processor resources on the players, most likely. That is something you would need to determine by trial and error with the actual hardware you are using.

**Comment by brunchboy** [comment]
@daffron there have been several more fixes in the last week or so, you should probably pull down a new preview build if you haven’t recently. And you have a show coming up soon, right?

**Comment by brunchboy** [comment]
@daffron did you have your show yet? Did things work properly with six players? I am finishing a huge new feature, #119 and would like to release Beat Link Trigger version 7 soon. So confirmation about this would be very helpful.

**Comment by daffron** [comment]
Hey,

Sorry havent been able to yet - covid pushed back the dates, again and now
I dont even have a date anymore! I do have 4 here if there are any specific
tests you wanted me to do?

**Comment by brunchboy** [comment]
Oh, sorry to hear that, although I suppose that is not too surprising! In what country is the show? We are finally getting some forward motion with vaccination here in the USA, I will be receiving my second dose of the Moderna vaccine in just over a week myself.

Any news about the latest preview release working well with the CDJ-3000 will reassure me a bit. I really hope someone can try it with six of the beasts attached, though. I may have to release version 7 before that happens, at this rate, though. I can always release a patch if we find something doesn’t work.

I will probably end up having to buy or rent at least one myself sometime soon because I really want to implement support for the much-closer tracking of DJ jumps, loops, and scratches that will be possible using a new packet type that it sends.

**Comment by brunchboy** [comment]
I’ll probably be closing this and shipping BLT version 7 soon, it has been sitting in pre-release too long. If anyone can do a real test with six players in the near future and report back here, I would really appreciate it! Otherwise, if any bugs remain, we will have to fix them in a patch release once they are reported.
