### ISSUE TITLE
Copy a show file to a different computer for offline editing - does not work.

### ISSUE THREAD

**Issue by whoman321** [Deep-Symmetry/beat-link-trigger#114]
Hello,

I have 2 computers with BLT:
1.  Home computer for offline editing
2.  Laptop for use with CDJs

Yesterday, I used my laptop to connect to a friend's CDJ, created a new show file, imported 3 tracks, and created some cues.
Everything worked out great.

Today, I'm at home and don't have access to the CDJs.  When I open up the show file on the laptop which I created it on, everything opens up properly, and I can edit the tracks in offline mode.

So I copied the BLS file from my laptop to my home computer so that I can edit the cues.
**When I open the BLS show file on my home computer, its is completely blank.  No tracks.  No Cues.**

Are there other files that I need to copy over in order to be able to open the show file on my home computer with tracks and cues?

**Comment by brunchboy** [comment]
Hello again! This kind of question is better suited to the Gitter chat, where other users can help answer it. I assume you are talking about the `.blts` show file? That should contain everything in the show. It is actually a Zip file which you could examine with a Zip extractor to see what is actually in it. (You may need to add the `.zip` extension for that to work, and I would suggest working with a copy.) But you should be able to move show files from computer to computer; I even have some linked to from the user guide for such purposes. Something else must be going wrong. Did you see any errors in the log?

**Comment by brunchboy** [comment]
I would suggest not trying to copy a `.blts` file while it is open in Beat Link Trigger, though, it might be in an intermediate state that would not be openable.

**Comment by whoman321** [comment]
Thanks for the quick reply.  There is an exception in the log file, but based on what you just mentioned, I decided to double check on another (3rd) computer, and it does work perfectly.

The home computer I was trying to use the file on has Xorg, but doesn't contain any window manager.  I think perhaps the BLT show interface isn't functioning properly because of this.  Interestingly enough, the Triggers interface works perfectly.

I'll do some more research on the exception as it relates to Xorg (with no window manager) in the next few days, and if it turns out to be something that can be investigated further or fixed, I'll let you know and we can reopen at that point.

Thanks again bud!

```2020-Dec-17 16:49:44 INFO [beat-link-trigger.core:114] - Giving up attempt to go online, user wants to continue offline.
2020-Dec-17 16:50:01 ERROR [beat-link-trigger.logs:55] - Uncaught exception on AWT-EventQueue-0
                                             java.awt.EventDispatchThread.run  EventDispatchThread.java:   90
                                      java.awt.EventDispatchThread.pumpEvents  EventDispatchThread.java:  101
                                      java.awt.EventDispatchThread.pumpEvents  EventDispatchThread.java:  109
                          java.awt.EventDispatchThread.pumpEventsForHierarchy  EventDispatchThread.java:  113
                             java.awt.EventDispatchThread.pumpEventsForFilter  EventDispatchThread.java:  124
                          java.awt.EventDispatchThread.pumpOneEventForFilters  EventDispatchThread.java:  203
                                            java.awt.EventQueue.dispatchEvent           EventQueue.java:  742
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege     ProtectionDomain.java:   85
                                  java.security.AccessController.doPrivileged      AccessController.java     
                                                    java.awt.EventQueue$5.run           EventQueue.java:  743
                                                    java.awt.EventQueue$5.run           EventQueue.java:  745
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege     ProtectionDomain.java:   95
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege     ProtectionDomain.java:   85
                                  java.security.AccessController.doPrivileged      AccessController.java     
                                                    java.awt.EventQueue$4.run           EventQueue.java:  715
                                                    java.awt.EventQueue$4.run           EventQueue.java:  721
                                        java.awt.EventQueue.dispatchEventImpl           EventQueue.java:  772
                                             java.awt.Component.dispatchEvent            Component.java: 4843
                                            java.awt.Window.dispatchEventImpl               Window.java: 2772
                                         java.awt.Container.dispatchEventImpl            Container.java: 2307
                                 java.awt.LightweightDispatcher.dispatchEvent            Container.java: 4488
                             java.awt.LightweightDispatcher.processMouseEvent            Container.java: 4547
                            java.awt.LightweightDispatcher.retargetMouseEvent            Container.java: 4918
                                             java.awt.Component.dispatchEvent            Component.java: 4843
                                         java.awt.Container.dispatchEventImpl            Container.java: 2321
                                         java.awt.Component.dispatchEventImpl            Component.java: 5011
                                              java.awt.Container.processEvent            Container.java: 2263
                                              java.awt.Component.processEvent            Component.java: 6400
                                     javax.swing.JComponent.processMouseEvent           JComponent.java: 3342
                                         java.awt.Component.processMouseEvent            Component.java: 6635
                                   java.awt.AWTEventMulticaster.mouseReleased  AWTEventMulticaster.java:  297
                 javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased      BasicMenuItemUI.java: 1064
                               javax.swing.plaf.basic.BasicMenuItemUI.doClick      BasicMenuItemUI.java: 1020
                                           javax.swing.AbstractButton.doClick       AbstractButton.java:  369
                                    javax.swing.DefaultButtonModel.setPressed   DefaultButtonModel.java:  262
                           javax.swing.DefaultButtonModel.fireActionPerformed   DefaultButtonModel.java:  405
                           javax.swing.AbstractButton$Handler.actionPerformed       AbstractButton.java: 2308
                               javax.swing.AbstractButton.fireActionPerformed       AbstractButton.java: 1967
      seesaw.action.proxy$javax.swing.AbstractAction$ff19274a.actionPerformed                                
                                                      seesaw.action/action/fn                action.clj:   90
                                                    beat-link-trigger.logs/fn                  logs.clj:   18
                                                        java.awt.Desktop.open              Desktop.java:  429
                                                sun.awt.X11.XDesktopPeer.open         XDesktopPeer.java:   87
                                              sun.awt.X11.XDesktopPeer.launch         XDesktopPeer.java:  124
```

**Comment by brunchboy** [comment]
Thanks for the update! That looks like an incomplete log, as I can’t see the actual exception that occurred, but your investigation sounds plausible. The show interface is certainly a lot more complex than the triggers interface, and may rely on features of a window manager. I have no idea how java interacts with them, though, it’s been a long time since I tried using Java on Linux, and that was all server-side development with no local GUI anyway.

I really appreciate your thoughtful research.

**Comment by whoman321** [comment]
Yup you're right... I seem to have missed the last 3 lines of that log.  After seeing those lines, it shows that the exception was actually from me trying to view the log file through the HELP menu option.  Since I have no GUI file manager, that makes perfect sense.  So I restarted BLT and opened the show file, and there is no exception at all.  But yes I'm still pretty sure this is because of the 'no window manager' issue.  

I'll research further and see what I can find, perhaps with verbose output.
Thanks much!

```
                    java.io.IOException: Failed to show URI:file:/tmp/blt_logs1608252560617-153516949/
java.security.PrivilegedActionException: 
java.security.PrivilegedActionException: 
```
