### ISSUE TITLE
Quitting BLT can leave Carabiner running?

### ISSUE THREAD

**Issue by brunchboy** [Deep-Symmetry/beat-link-trigger#124]
I noticed while testing the Apple Silicon native versions of Carabiner and CoreMidi4J embedded in BLT 7 snapshot that quitting Beat Link Trigger while its managed Carabiner instance was running seemed to leave that Carabiner running in the background. This isn’t a big problem, but it wasn’t intended; I had assumed that once the parent process ended, that would kill Carabiner as well.

Since it doesn’t seem to, it’s worth adding some more code to the shutdown hook which explicitly tells beat-carabiner to stop any Carabiner process that it has started.

**Comment by VNRARA** [comment]
A task manager force close also keeps carabiner open.

**Comment by brunchboy** [comment]
Yes, @VNRARA, that is inevitably going to be true; if you force close BLT, then BLT cannot run its code which kills Carabiner.
