### ISSUE TITLE
Start/Remaing Time not sent by Pioneer CDJ 2000 (Not nexus)

### ISSUE THREAD

**Issue by djkad** [Deep-Symmetry/beat-link-trigger#131]
I've tested the application with a pair of pioneer cdj2000 but there is no indication about start/remaining track time, probably because that kind of informations are not send by non-nexus cdjs.
I wanted to use for send Midi/Osc messages + Smpte info to other software (Qlc+ and Resolume) with no luck.
I wrote here because since i've lost lot of time figuring it out, i think it could be useful for other cdj2000 users.

**Comment by brunchboy** [comment]
Hi, this is expected and explained in the project page’s [Compatibility section](https://github.com/Deep-Symmetry/beat-link-trigger#compatibility). The non-nexus players do not send enough information to enable most of the features of Beat Link Trigger. There is nothing that can be done about that at our end, and Pioneer is not likely to upgrade the firmware of the non-nexus players to add nexus features, they would prefer you buy new hardware.

**Comment by djkad** [comment]
Thanks a lot. I was thinking to try with wireshark but probably you have already investigated a lot about it.

**Comment by brunchboy** [comment]
Yes, the things we have figured out are all described here: https://djl-analysis.deepsymmetry.org/djl-analysis/packets.html

This section explains the data that is missing on pre-nexus players that prevents us from figuring out their playback position: https://djl-analysis.deepsymmetry.org/djl-analysis/vcdj.html#cdj-status-packets
