### ISSUE TITLE
Issue with Remixer field from Rekordbox

### ISSUE THREAD

**Issue by Hallucyn8** [Deep-Symmetry/beat-link-trigger#132]
Issue discovered when playing tracks from Rekordbox in Export/Link mode that is stopping the web page served by the OBS Web Server in Beat Link Trigger auto-refreshing on master player change.

Issue is present in both BLT 0.6.3 and the 7.0.0 snapshot.

I am using an XDJ-XZ, a Windows 10 laptop running Rekordbox 6.5.3 and a Windows 10 PC running BLT that is used for streaming with OBS.

When using the XZ in standalone mode playing tracks from USB the issue is not present and the web page auto-refreshes as expected.

When connecting Rekordbox in Export/Link mode the web page stops auto-refreshing. A manual fresh of the page will update with the correct information. Browsing to /params.json returns the following error:

Cannot JSON encode object of class: class org.deepsymmetry.beatlink.data.SearchableItem: SearchableItem[id:0, label:]

When using the Inspect Template Parameters function of the OBS Web Server and comparing the Remixer field of a track loaded from USB and one loaded from Rekordbox (which have no remixer data present on the file) the track from USB will show a blank value but the one loaded from Rekordbox shows SearchableItem[id:0, label:]

Repeating the same test with a track that does have the Remixer field populated, the same track loaded on player 1 and player 2 with player 1 loaded from USB and player 2 loaded from Rekordbox, the track loaded from USB still shows the Remixer field as blank but the track loaded from Rekordbox shows the same text as above but with values for id and label, e.g. SearchableItem[id:1234567890, label:remixername]

Looking at the info of both of these tracks directly on the XZ shows the correct value for Remixer.

**Comment by brunchboy** [comment]
Sorry it took so long for me to get to this! If you have a chance, could you verify if the latest preview build of Beat Link Trigger fixes it? I don’t generally have two machines around in order to run rekordbox on one, and BLT on another (to cause the empty remixer fields to be present), and my tracks generally lack remixers. But BLT was acting as if this data was a string, not a `SearchableItem`, which would never work, and would lead to the exact error you reported, so I am fairly confident that my fix will work.

**Comment by Hallucyn8** [comment]
I've only done a quick test but it definitely seems to have resolved the issue, I'm getting the overlay web page updating on master player change for both tracks loaded from USB and from Rekordbox so all looks good. Thanks for fixing it

**Comment by brunchboy** [comment]
Excellent, thanks so much for responding so quickly after I had lost track of this issue for so long, @Hallucyn8!
