### ISSUE TITLE
Closing BLT via task manager keeps carabiner open.

### ISSUE THREAD

**Issue by VNRARA** [Deep-Symmetry/beat-link-trigger#138]
**Describe the bug**

**To Reproduce**
Close BLT via task manager.

**Expected behavior**
A check to see if BLT is still open and auto close itself; but it stays running in the background preventing another instance from using the port. 

**Screenshots**
![image](https://user-images.githubusercontent.com/3942672/183501960-3da3cf87-7934-4113-bab5-b6840cb6c20f.png)

**Exceptions and Stack Traces**
NA

**Desktop (please complete the following information):**
 - Beat Link Triger Version: Version: 7.0.1
 - Java Version: 11.0.15, OpenJDK 64-Bit Server VM, Amazon.com
 - OS: Windows 10 Home  21H2  5-‎8-‎2022 19044.1826

**Additional context**
If unaware the user will not find carabiner open in taskbar so it'll induce the port is being used problem.

**Comment by brunchboy** [comment]
This should not be a problem; Carabiner is designed to run outside the context of BLT. You can install it and launch it manually before running BLT, and BLT will find it and use it rather than trying to launch its own copy. If you are running into issues with the port already being in use, then it means something has gone wrong with Carabiner itself. You’ll need to dig a bit deeper. Carabiner is never going to quit itself just because BLT is not running, Carabiner is used in many projects that have nothing to do with BLT.

**Comment by brunchboy** [comment]
In general, however, I would discourage the practice of killing BLT using the task manager; it prevents it from doing important cleanup, and can cause loss of data that it would have otherwise warned you about and prompted you to save.

**Comment by brunchboy** [comment]
I wonder if this might be a Windows firewall issue? In any case, I will leave this ticket open for a while in case you can find and share more details about what is actually causing the problem. If nothing else, that could lead to another entry in the troubleshooting guide.

**Comment by VNRARA** [comment]
"killing BLT using the task manager;" I only did that after having some connection issues, thinking the killing the blt-proces would also fix the carabiner issue, not knowing carabiner was a seperate exe running. I thought that ideally a helper type app would close itself after not find a connection with the main program.

**Comment by brunchboy** [comment]
Carabiner is its own thing. It can be used by multiple applications at once, or simply wait until an application wants to use it.

**Comment by brunchboy** [comment]
If I hear nothing more about this, I will close the issue shortly.

**Comment by VNRARA** [comment]
Haven't been able too use for a while too sadly.
