### ISSUE TITLE
TrackPositionListener not working with Shallow Playback Simulator

### ISSUE THREAD

**Issue by RoL0NL** [Deep-Symmetry/beat-link-trigger#170]
When trying to setup an LTC timecode output using the ["LTC using an Orange Pi"](https://blt-guide.deepsymmetry.org/beat-link-trigger/7.1.0/Integration_SMPTE.html#smpte-orange-pi)  instructions on the ["Integration examples/SMPTE Linear Timecode"](https://blt-guide.deepsymmetry.org/beat-link-trigger/7.1.0/Integration_SMPTE.html) page and testing this setup using the [Shallow Playback Simulator](https://blt-guide.deepsymmetry.org/beat-link-trigger/SimulatingPlayback.html) I get NullPointer exceptions when trying to simulate the 'Loaded Expressions' for tracks. It seems that the `loaded-players` variable does not exist (returns `nil`) and that the `org.deepsymmetry.beatlink.data.TrackPositionListener` does not trigger correctly on changes in track positions as `position-update` also returns `nil`.

 **Can it be that these (`loaded-players` and the `TrackPositionListener`  are not (correctly) implemented for the playback simulator (yet)?**

**To Reproduce**
1. Start Beat Link Triggers with a fresh config in offline mode.
2. Load [this](https://blt-guide.deepsymmetry.org/beat-link-trigger/7.1.0/_attachments/OrangePiSMPTE.bls) show from the ["LTC using an Orange Pi"](https://blt-guide.deepsymmetry.org/beat-link-trigger/7.1.0/Integration_SMPTE.html#smpte-orange-pi) page. Follow the instructions to configure OSC.
3. Open the Shallow Playback Simulator via Network > New Playback simulator.
4. Move the contents of the 'Came Online' Expression to the 'Global Setup' Expression, as the 'Came Online' Expression will not trigger in offline mode.
5. Select a track in the Shallow Playback Editor, press play, seek with Needle Drop. (still nothing will happen)
6. Go to the loaded expression of a track in the show, press 'Simulate'

**Expected behavior**
Receive updates about the track state in the OSC server

**Exceptions and Stack Traces**
```
Problem simulation expression.

java.lgn.NullPointerException: Cannot invoke "java.util.concurrent.PriorityBlockingQueue.put(Object)"

You may wish to check the log file for the detailed stack trace.
```

Log:
```
2023-Aug-20 14:36:44 ERROR [beat-link-trigger.editors:1899] - Problem simulating expression:
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.PriorityBlockingQueue.put(Object)"
                                               java.awt.EventDispatchThread.run
                                        java.awt.EventDispatchThread.pumpEvents                                    (repeats 2 times)
                            java.awt.EventDispatchThread.pumpEventsForHierarchy
                               java.awt.EventDispatchThread.pumpEventsForFilter
                            java.awt.EventDispatchThread.pumpOneEventForFilters
                                              java.awt.EventQueue.dispatchEvent
  java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege
                                    java.security.AccessController.doPrivileged
                                                      java.awt.EventQueue$5.run                                    (repeats 2 times)
  java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege                                    (repeats 2 times)
                                    java.security.AccessController.doPrivileged
                                                      java.awt.EventQueue$4.run                                    (repeats 2 times)
                                          java.awt.EventQueue.dispatchEventImpl
                                               java.awt.Component.dispatchEvent
                                              java.awt.Window.dispatchEventImpl
                                           java.awt.Container.dispatchEventImpl
                                   java.awt.LightweightDispatcher.dispatchEvent
                               java.awt.LightweightDispatcher.processMouseEvent
                              java.awt.LightweightDispatcher.retargetMouseEvent
                                               java.awt.Component.dispatchEvent
                                           java.awt.Container.dispatchEventImpl
                                           java.awt.Component.dispatchEventImpl
                                                java.awt.Container.processEvent
                                                java.awt.Component.processEvent
                                       javax.swing.JComponent.processMouseEvent
                                           java.awt.Component.processMouseEvent
org.pushingpixels.substance.internal.utils.RolloverButtonListener.mouseReleased  RolloverButtonListener.java:  108
                       javax.swing.plaf.basic.BasicButtonListener.mouseReleased
                                      javax.swing.DefaultButtonModel.setPressed
                             javax.swing.DefaultButtonModel.fireActionPerformed
                             javax.swing.AbstractButton$Handler.actionPerformed
                                 javax.swing.AbstractButton.fireActionPerformed
        seesaw.action.proxy$javax.swing.AbstractAction$ff19274a.actionPerformed
                                                        seesaw.action/action/fn                   action.clj:   90
                        beat-link-trigger.editors/build-show-simulate-action/fn                  editors.clj: 1897
                                                beat-link-trigger.editors/fn/fn                  editors.clj:  638
                                 beat-link-trigger.editors/simulate-track-event                  editors.clj:  593
                           beat_link_trigger.expressions$eval341$fn__343.invoke               NO_SOURCE_FILE:    4
          beat_link_trigger.expressions$build_orangepi_position_listener.invoke               NO_SOURCE_FILE:    1
    beat_link_trigger.expressions$build_orangepi_position_listener.invokeStatic               NO_SOURCE_FILE:   29
                                                                            ...
                                                          overtone.osc/osc-send                      osc.clj:  118
                                                          overtone.osc/osc-send                      osc.clj:  122
                                                      overtone.osc/osc-send-msg                      osc.clj:   15
                                                overtone.osc.peer/peer-send-msg                     peer.clj:  418
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.PriorityBlockingQueue.put(Object)"
```
**Further steps**

1.  Fix the player number to '1' by changing `(let player     (first loaded-players))` into `(let player    1)`
 
The null pointer exception is gone, I do receive `rate/set` and `direction` messages, but the 'TrackPositionListener' does not forward `pitch`, `start` and `goto` messages, as `position-update` always returns `nil`.

**Desktop (please complete the following information):**
 - Beat Link Triger Version: 7.2.0
 - Java Version: 17.0.8, OpenJDK 64-Bit Server VM
 - OS: Windows 11 Version 22H2 (OS Build 22621.2134)

**Comment by brunchboy** [comment]
Hello! Thank you for the detailed report. Unfortunately this is not surprising, that is why the simulator is called “shallow”. As the [user guide](https://blt-guide.deepsymmetry.org/beat-link-trigger/7.2.0/SimulatingPlayback.html) states:

> The most meaningful and reliable way to do this, of course, is to connect some actual player hardware, take Beat Link Trigger online, load up a track, and play it. This lets your expressions access all the data available through the Beat Link library, and lets you see how your cues and triggers line up with the audio of the track itself.

The [`TrackPositionListener`](https://deepsymmetry.org/beatlink/apidocs/org/deepsymmetry/beatlink/data/TrackPositionListener.html) is part of the [Beat Link library](https://github.com/Deep-Symmetry/beat-link#beat-link). It does not (and cannot) know anything about Beat Link Trigger, nor its shallow playback simulation. If you need to test code that works at that deep a level, there is no alternative to having an actual player available so you can take BLT online.

It may be worth calling out this limitation more explicitly in the user guide, using your situation as a specific example of when you need to escalate to testing with actual player hardware.

It sounds like you are doing some interesting work, I hope you will consider joining the [Zulip community](https://deep-symmetry.zulipchat.com/#narrow/stream/275322-beat-link-trigger) to discuss it, and explore options for going further!

**Comment by RoL0NL** [comment]
Hi! Thank you for your reaction. This is indeed what I expected, thank you for confirming and explaining. Next week I will have access to some actual player hardware. If I find solutions that might be useful for others, I will share it in the Zulip community for sure!
