### ISSUE TITLE
Quick Question more than bug report.

### ISSUE THREAD

**Issue by sappy96** [Deep-Symmetry/beat-link-trigger#171]
Not really bug,

Just want to know if theres a problem with Ableton link in version 7.20.

I have installed the app on Mac (M1 Macbook air - 13.4) and windows 10. The app sees my XDJ-700 and in the Trigger window I can see track names and bpm changes etc.. But when I click on ableton link option I dont get any popup or configuration window like the manual. So cant get It to send the Ableton link message.

Have I missed something? Tried using DMG, exe and .Jar turned off all security/firewalls on Mac and Windows when trying.

**Comment by brunchboy** [comment]
Please don’t use issues for discussion and questions, that’s what the [Zulip community](https://deep-symmetry.zulipchat.com/#streams/275322/beat%20link%20trigger) is for. As a quick answer, though, I am not aware of any issues with Carabiner / Ableton Link in 7.20, and there have not been any changes there for a long time, so we will need to look at your log files and see if we can find explanatory exceptions once you join the chat.
