### ISSUE TITLE
Possible to add Pioneer Opus Quad Support?

### ISSUE THREAD

**Issue by hrtbrkd** [Deep-Symmetry/beat-link-trigger#173]
just putting this request out for the project.

**Comment by brunchboy** [comment]
Hello, @hrtbrkd, please don’t use the issue tracker as a place to have conversations. This question has been discussed in the Zulip community here: https://deep-symmetry.zulipchat.com/#narrow/stream/275322-beat-link-trigger/topic/New.20Opus.20Quad.20hardware

In short, there is no reason to believe that the Opus Quad hardware can synchronize with CDJ hardware, so it cannot work with Beat Link Trigger either.
