### ISSUE TITLE
Start show from command line argument

### ISSUE THREAD

**Issue by timewasternl** [Deep-Symmetry/beat-link-trigger#174]
**Is your feature request related to a problem? If so, please describe.**
Currently I am autostarting BLT on my Raspberry Pi and I have to select the bls file everytime prior to playing my set.

**Describe the solution or new capability you’d like**
It would be great if I could extend my startup command to ```java -jar beat-link-trigger.jar --show my-show.bls``` and have it automatically open the show window.

**Describe alternatives you've considered**
As it is a quality of life improvement, the alternative will be to do it manually each time.

**Current Beat Link Trigger Version**
v7.2.1

**Additional context**
None

**Comment by brunchboy** [comment]
Hello, @timewasternl and thank you for the interesting idea. It needs some further discussion to flesh out the approach, but once these details are settled, I’d be happy to accept a PR that implements the decisions (it seems like an excellent small project for someone new to the project to tackle), or to queue it up to implement myself.

That kind of discussion is best had in the [Zulip discussion stream](https://deep-symmetry.zulipchat.com/#narrow/stream/275322-beat-link-trigger). Would you be willing to jump in there and open this as a topic?

Some of the questions I want to discuss are:
  * Are you wanting to invoke BLT with different arguments to open different shows? If not, whenever you launch BLT the shows that you had open on your last run should be reopening. If that is not happening, we need to do some debugging about your environment to figure out why not.
  * Assuming you do want to be able to open different shows with different command-line arguments, should the presence of any `--show` arguments suppress the automatic reopening of previous shows that normally occurs? I would think the answer would be yes, or we would want to add another argument to suppress that.
  * I should be explicit about an assumption I made in the above bullet: we should probably support multiple `--show` arguments to open multiple shows.
  * And while we are making these changes, we probably want another argument which tells BLT to not reload the trigger configuration that is found in the Java preferences, and instead load a triggers file.

**Comment by brunchboy** [comment]
This has been implemented in the latest preview build available at the top of the Releases section. The new documentation is here: https://blt-guide.deepsymmetry.org/beat-link-trigger/README.html#command-line-arguments

**Comment by brunchboy** [comment]
For posterity, the discussion occurred in [this Zulip topic](https://deep-symmetry.zulipchat.com/#narrow/stream/275322-beat-link-trigger/topic/Open.20show.20from.20command.20line.20argument).

When you have a chance to try this out, let me know, and either close the issue or let me know to do it. Thanks for the idea!

**Comment by brunchboy** [comment]
If I don’t hear anything back within a few days, I’ll close the issue as complete.
