### ISSUE TITLE
Allow shows to contribute triggers

### ISSUE THREAD

**Issue by brunchboy** [Deep-Symmetry/beat-link-trigger#176]
**Describe the solution or new capability you’d like**

If shows could contain trigger definitions, which appear in the Triggers window when the show is open, but go away when it is closed, it would be possible to consolidate most, or perhaps all, of the integration examples into standalone show files, making them far easier for non-programmers to try out and use.

Since Show files are zip archives, they are compact and easy to distribute; we could set up a page hosting all the integration examples, along with contributions from users, making it easier to grow the BLT ecosystem.

**Describe alternatives you've considered**

@drummerclint proposed something slightly different, a menu allowing people to create a trigger from a set of built-in templates, such as OSC tap tempo. The problem with that is that a trigger on its own is not enough, it needs a related set of shared functions, startup, shutdown, and other expressions. Trying to manage those in a safe way when multiple templates are modifying the configuration file would be a nightmare.

**Additional context**

The mechanism that I created for the [Xone mixer channels-on-air integration example](https://blt-guide.deepsymmetry.org/beat-link-trigger/7.2.0/Integration_XoneOnAir.html) would allow these shows to offer a simple GUI where users could configure the details necessary for the integration (such as the OSC server and path that the tempo tap messages should be sent to). This would mean that most users would not need to worry about, edit, or even see the underlying Clojure code until the day where they get curious about how things are actually implemented.

**Comment by brunchboy** [comment]
@drummerclint I think this is pretty much ready to go, but if you have some OSC tap tempo code you can share as another example we can bundle up with it, I’d like that.

**Comment by drummerclint** [comment]
Hey @brunchboy, this is the OSC tap tempo trigger I use with Chamsys.
[2023-11-07 - OSC Tap Tempo.zip](https://github.com/Deep-Symmetry/beat-link-trigger/files/13291895/2023-11-07.-.OSC.Tap.Tempo.zip)
I had to zip it for github to allow the attachment

**Comment by brunchboy** [comment]
Thanks, @drummerclint, that looks great. A slightly different example than the one I built for QLC+ but it can build on it, just adding a text field for you to edit what you want your OSC message to be. Although… why do you need to send six separate OSC messages on each beat? Maybe we should move to Zulip for this kind of back-and-forth discussion. I hope you’ve seen all the great progress we’ve been making there, including coexisting with peacefully with CDJ-3000s even when they are set to Player 5 or 6 now! 😄
