### ISSUE TITLE
Detect loss of network 

### ISSUE THREAD

**Issue by brunchboy** [Deep-Symmetry/beat-link-trigger#18]
Markus Krooked reported that sometimes when one of his CDJs loses power, it is still not usable when it comes back. If that can be reproduced and resolved, great. But more plausibly, if we stop getting packets from anyone for too long, go offline and offer to start over?

**Comment by brunchboy** [comment]
Now that there is offline/online support this might be easier. In fact, probably the best thing to do is to make the Triggers window open right away and stay open during the attempt to start the Virtual CDJ. Rather than periodically showing an options dialog, the connection in progress window could have Quit and Stay Offline buttons, which would cancel the connection attempt. And the Network menu could get an automatic reconnect checkbox, which when we lose all our devices for more than a few seconds, shuts down the Virtual CDJ and tries to go back online.

**Comment by bukarti88** [comment]
how can i open the virtual cdj wındow

**Comment by brunchboy** [comment]
You would have to write code to create one first. Such a concept has not been implemented yet.

**Comment by bukarti88** [comment]
Are you going to make one or this feature is for an other relases s


16 Ara 2016 6:39 PM tarihinde "James Elliott" <notifications@github.com>
yazdı:

**Comment by brunchboy** [comment]
What do you have in mind? There is already a specific issue about this, #3 which has some ideas. Recently I also have been thinking about adding a metadata cache, to reduce query traffic to the CDJs. That would fit nicely in such a window. What specific features are you thinking about, though?

Also, this project is designed to be a playground to make it easy for anyone to build anything. So please fork it and try your own hand at implementing windows that do what you want! 😁

**Comment by brunchboy** [comment]
This is going to become critical as I start working on supporting headless operation. When all devices disappear from the `DeviceFinder`, the VirtualCDJ should go back to searching for a DJ Link network, so that it can reconfigure itself as necessary if we connect to a new network.

**Comment by brunchboy** [comment]
This was fixed by an underlying Beat Link fix in the issue referenced above (and became a lot less important when BLT started using Crate Digger for most metadata operations).
