### ISSUE TITLE
Player status drawing a blank window (raspberry pi OS / openjdk-17)

### ISSUE THREAD

**Issue by jwaeles** [Deep-Symmetry/beat-link-trigger#188]
First of all, thank you for the software. I run it since 2-3 years at the club I work at as a lighting technician. It was used successfully on a LOT of USB's from headliners of the underground house scene. If they don't play exclusively vinyl and if they analyzed their tracks, then beat-link-trigger helped me, night after night, every weekend since after lockdown. 

My back is starting to ache from carrying my heavy laptop every weekend to run BLT on, so I thought of leaving a dedicated Raspberry Pi 4 at the club to run beat-link-trigger on. Alas, it doesn't seem to work on RPI 4.

**Describe the bug**
I'd like to use Beat Link Trigger on a raspberry pi 4, Raspberry pi OS, 8 GB RAM, 64 bits, connected to XDJ XZ. The "Player Status" window is empty.

**To Reproduce**
1. Get a raspberry pi 4b
2. Install the default desktop raspberry pi OS 64 bits
3. sudo apt install default-jre
4. sudo ip a add dev eth0 169.254.0.99/16
5. java -jar beat-link-trigger-7.4.1.jar
6. beat-link-trigger finds the XDJ, click on Player Status
7. The window is all grey with just one of the zoom sliders. Moving the pitch redraws the tempo / BPM info, but the rest of the window never gets drawn.

**Expected behavior**
Player status should show both player infos, waveforms scrolling and all that.

**Screenshots**
![20241122_18h35m50s_grim](https://github.com/user-attachments/assets/533f4959-6a64-4f1b-8fde-8f90eea9a96f)

**Exceptions and Stack Traces**
If possible, copy and paste or attach as much of the log file as needed to show where things were going wrong or not working as expected.
[blt.log](https://github.com/user-attachments/files/17874384/blt.log)

**Desktop (please complete the following information):**
 - Beat Link Triger Version: 7.4.1
 - Java Version: 17.0.13, OpenJDK 64-Bit Server VM, Debian
 - OS: Linux raspberrypi 6.6.51+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.51-1+rpt3 (2024-10-08) aarch64 GNU/Linux

**Additional context**
I'm unable to test with JRE 11, as it isn't provided on raspberry pi / debian apt. I have an ubuntu laptop with openjdk-11-jre and that one works just like my windows laptop, so it's not a bug with all linux versions.

Thanks!

**Comment by brunchboy** [comment]
Hi! This isn’t likely to be a bug or issue with BLT, as I have used it on a Pi 4, and it doesn’t have OS-specific dependencies when it comes to player status. Please use the [Zulip community](https://deep-symmetry.zulipchat.com/#narrow/channel/275322-beat-link-trigger) to get help in exploring things like this, and only open issues when they have actually been confirmed as a problem with BLT or one of the underlying projects after discussion there, and you’ve been asked to do so. Hopefully once you ask the questions there, I or another member of the community will help you figure out how to troubleshoot your setup and get it working. That platform is much better for free form discussion and has a larger audience to help you, and keeping such things out of the issues helps keep the projects manageable.

**Comment by jwaeles** [comment]
As an extra note, I have tested three instances of BLT with my XDJ XZ at home

* Windows 11 laptop with beat-link-trigger 7.4.1 : no problem
* Ubuntu 22 laptop with beat-link-trigger 7.4.1 (openjdk-11) : no problem
* Raspberry pi OS raspberry pi 4 64 bits (openjdk-17) : the bug described here above
