### ISSUE TITLE
Rekordbox - Ableton Link, BPM, signal out in performance mode.

### ISSUE THREAD

**Issue by dezmontnikus** [Deep-Symmetry/beat-link-trigger#189]
is it possible to implement a function in the BLT program so that it retrieves data from RK, in the way this script does?

https://github.com/grufkork/rkbx_osc

This would allow connecting BLT to RK from e.g. FLX-4, FLX-10. It would be possible to control Resolume via the BMP synchronization signal.

**Comment by brunchboy** [comment]
Please use the Zulip community to get help in exploring things like this, and only open issues when they have actually been confirmed as a problem with BLT or one of the underlying projects after discussion there, and you’ve been asked to do so. That platform is much better for free form discussion and has a larger audience to help you, and keeping such things out of the issues helps keep the projects manageable.

That said, I can already say that this is not something that belongs in Beat Link Trigger: this project is for working with Pro DJ Link, not performance mode, nor snooping inside the rekordbox process. You will have better luck asking this other project to add Ableton Link support, perhaps with the help of my Carabiner library.

**Comment by brunchboy** [comment]
You can find the Zulip community here: https://deep-symmetry.zulipchat.com/#narrow/channel/275322-beat-link-trigger
