### ISSUE TITLE
Additional field in Player Status window in addition to Artist and Trackname

### ISSUE THREAD

**Issue by BrainShit** [Deep-Symmetry/beat-link-trigger#190]
**Describe the solution or new capability you’d like**
The ability to choose an additional field to display in the Player Status window. As it currently only shows title and artistname and I personally use the Comments field to communicate some Information to my VJ who uses toe Player Status to know what I'll be playing next.

**Describe alternatives you've considered**
We considered using the http-server based OBS overlay that is included but running an extra http server and a browser just to get the info feels a bit overkill.

**Current Beat Link Trigger Version**
7.4.1

**Additional context**
Personally I'd also be fine with it showing the "Comments" field by default instead of a choosable field. Or a very quick explanation of what I'd need to change to have this added myself as I've never used clojure before :D

**Comment by brunchboy** [comment]
Please have exploratory discussions like this in the [Zulip community](https://deep-symmetry.zulipchat.com/#narrow/channel/275322-beat-link-trigger), and once consensus has been reached about a change, then it’s time to open an issue. This is the first time I’ve heard a request along these lines, though I can certainly see how it could be useful. You may be able to hot-patch the existing player status code through the global setup expression to achieve what you want, I’ll try to find some time to explore that.

**Comment by brunchboy** [comment]
Yeah, it’s too hacky even for me to try to hot-patch the existing code via the player status window. What I‘ll do is add a way for you to supply your own expression that gets called with the device number and track metadata and returns the string to be displayed, so it would be simple to supply a function that returns the comment from the metadata.

**Comment by brunchboy** [comment]
Ok, I’ve made those changes. Once the pipeline completes here on GitLab, you can upgrade to the latest [preview release](https://github.com/Deep-Symmetry/beat-link-trigger/releases/tag/latest-preview), and then add this to your Global Setup Expression:

```
(replace-artist-line (fn [metadata _player] (.getComment metadata)))
```

**Comment by brunchboy** [comment]
The pipeline has progressed far enough that the preview release version of the online user guide explains this new feature in the [Global Setup Expression section](https://blt-guide.deepsymmetry.org/beat-link-trigger/Expressions_TriggerGlobal.html#global-setup-expression).

**Comment by brunchboy** [comment]
And the GitHub Actions pipeline completed successfully, so this is ready for you to try.

**Comment by brunchboy** [comment]
@BrainShit could you let me know if this is working for you?

**Comment by BrainShit** [comment]
Sorry I didn't notice that you already worked on this!
First sorry, I wasn't aware that I should've gone to zulip first.
Secondly, I'm personally currently lacking in ProDJLink supported Hardware and wasn't able to find anyone that'll let me test this real quick, so sorry there as well. 
I should be able to test this properly shortly before christmas however. 

So again sorry that this'll have to wait a bit longer. But either way thank you very much for working on this so quickly!

**Comment by brunchboy** [comment]
No worries! I just wanted to be sure you noticed there was something available for you to try when you have time, and you do now know that. 😄

**Comment by BrainShit** [comment]
Apologies for the very long silence on my part. Some stuff came up and I wasn't able to test this properly until recently. 
It worked perfectly! My VJ got all the info he needs to easily find all the clips.

So again thank you very much for enabling this option!

**Comment by brunchboy** [comment]
Great, thanks for taking the time to come back and report that, I appreciate it! And it’s normal for open-source projects like this to pause unpredictably.
