### ISSUE TITLE
Add expression that runs when going online

### ISSUE THREAD

**Issue by brunchboy** [Deep-Symmetry/beat-link-trigger#60]
It would be nice to let people do things like always go into Carabiner sync modes when they go online, to help with recovery from network problems, etc. An expression that would run whenever BLT has gone online would allow this and more.

It might be nice to have one that runs when going offline as well.

**Comment by brunchboy** [comment]
This turns out to be a bit awkward, because sometimes we go online before the global setup expression runs, and sometimes (if the user decides to start offline) after. Trying to coordinate that, or explain that the two expressions can’t depend on a consistent ordering, would be complicated.

**Comment by nachtwanderer** [comment]
I am looking for something similar. I have installed BLT 0.5.3 on my Raspberry Pi and want to use it headless. This is why it would be nice to set up Sync-Modes and Carabiner Settings from Global Setup Expression. Maybe there is allready a workaround for my issue, but I could not figure it out by now.

I don't want to use beat-carabiner, because I want to add some triggers later.

**Comment by brunchboy** [comment]
Thanks for letting me know. I will go ahead and add this, and just document that you can’t count on the ordering (and remind people how to check if you are online in in Global Setup). I’d been leaving it undone since I didn’t know if anyone actually wanted it.

You are right that `beat-carabiner` is very limited by comparison. But it does have the advantage of being able to run in a truly headless situation (where the operating system does not allow Java to initialize Swing, the GUI environment). If you have been able to run BLT on your Pi, there must at least be some display that could be connected, even if you don’t always have one plugged in or turned on?

I would like to separate the runtime engine of BLT from the GUI, so they can run separately (and allow multiple different interfaces to talk to the same engine instance), and have some sketches of good ways to approach this, but since it will take hundreds of hours of challenging work, I may never have time to actually do it.

**Comment by nachtwanderer** [comment]
Thank you for the reply and for adding it.

You are right. I am using the Raspberry Pi with display and keyboard connected. That is also fine for setting everything up. I just want to use it without a display during my shows later.  My usecase is to run a small lightshow directly from the Raspberry Pi with QLC+ triggered by BLT.

**Comment by brunchboy** [comment]
Cool. And maybe someday you will want to investigate afterglow, my lighting software that led me to develop BLT (although to be honest it has a much steeper learning curve than QLC+) 😉 

I’m sorry I didn’t have time to get the actual expression implemented last night, although I did think through how I am going to do it and started laying the foundations. I have much more time free this evening, so I hope to get a new preview build out that you can test.

**Comment by nachtwanderer** [comment]
I willcheck out afterglow later. I am excited to try the new build and get it running. To be honest my experience in codeing and using compilers is low. Also it's the first time making a bigger project on the raspberry pi.

**Comment by brunchboy** [comment]
All right, the latest [preview JAR](https://github.com/Deep-Symmetry/beat-link-trigger/releases/download/v0.5.3/beat-link-trigger-0.5.4-PREVIEW.jar) has working Came Online and Going Offline expressions, and I was even able to come up with a sensible relationship between them and the Global Setup/Shutdown expressions. They make a lot of things much simpler in my examples, and even in things that I like to do (like automatically opening the Player Status window). Please give it a try @nachtwanderer and let me know if it helps you achieve your goals.

**Comment by nachtwanderer** [comment]
I just could try it and the "came online expression" works and is a good feature to achive my goals.

However, the function I am missing is something like:

---Came Online Expression---

1. (beat-link-trigger.carabiner/show-window nil)
2. (beat-link-trigger.carabiner/connect)
3. (beat-link-trigger.carabiner/sync-mode "Passive")
4. (beat-link-trigger.carabiner/ableton-link-sync)
5. (beat-link-trigger.carabiner/ableton-link-align-at-level-bar)

--------------------------------------------------------------------

Is there something like this? Maybe I cannot find it.

Thank you for your help.

**Comment by brunchboy** [comment]
No, unfortunately there is only support for items 1 and 2 on your wish list. I did not yet build ways for expressions to control other aspects of Carabiner. I am working on that now. In fact, your proposed approach for item 3 is a good one, I should be able to implement exactly that, although I need to add new kinds of error checking to work well in the context of expressions.

**Comment by brunchboy** [comment]
All right, I have implemented all of these features, and am uploading a new preview build. Steps 4 and 5 are a bit different than the way you suggested. You can find the details in the [Came Online Expression](https://beat-link-trigger-guide.netlify.com/beat-link-trigger/expressions#came-online-expression) section of the `master` branch of the online user guide (and also in the embedded version)

**Comment by nachtwanderer** [comment]
Wow. That was fast. I will give it a try later this day.

**Comment by brunchboy** [comment]
It was a little too fast; it was late, I was sleepy, and rushed it a bit. Using strings for the `sync-mode` argument is actually a poor and non-idiomatic Clojure API, even though it was the easiest first approach because I could just directly pass them to the menu. I will be changing them to keywords shortly, so you will need to instead use this for step 3:

```clojure
(beat-link-trigger.carabiner/sync-mode :passive)
```

**Comment by brunchboy** [comment]
OK, the API is fixed, and I have updated the preview release and the user guide. I’m glad I seem to have managed this before you tried adding the older-style code to your Came Online expression. Let me know how things go for you when you have a chance. I will probably add the ability to control other elements of the Carabiner window from expressions as well (such as choosing which CDJs are synced and which is the tempo master) as part of the final release. Thanks for the idea!

**Comment by nachtwanderer** [comment]
Thank you for this and BLT in general. It just works perfect for me. Now it can be a real turn key system. Your idea to add all the options from the carabiner window is a good one.

I also read a bit about your afterglow projekt, but it seams to be too much code based for my usecase, since I want to programm about 200 small lightshows for each Track, that I am using frequently in my DJ-Sets. Right now I need to setup the OSC connection between BLT and QLC+. I already receiving OSC Packets in QLC+ but no Values.

Anyway, is there a possibility to share some custom expressions with the community? I made some expressions that might be interesting for others.

**Comment by brunchboy** [comment]
That makes sense, when I heard that you were new to coding I realized that afterglow would not be a dood direction for you.

That would be great if you could share your expressions! I would encourage you to start by creating a page or two about them in the [wiki](https://github.com/Deep-Symmetry/beat-link-trigger/wiki) and then I can link to them from the relevant sections of the user guide when you are ready. 

Thank you for the feedback, I will leave this issue open until I have finished up the other functions I want to add to Carabiner.

**Comment by brunchboy** [comment]
You can also share your expressions on the [Gitter chat](https://github.com/brunchboy/beat-link-trigger) but adding them to the Wiki like Clint did is a more lasting and helpful approach. The best answer is probably both! Put them on the Wiki, then announce them on Gitter. 😄

**Comment by brunchboy** [comment]
The new list of functions that manipulate the Carabiner window is [here](https://beat-link-trigger-guide.netlify.com/beat-link-trigger/link#other-automation).
