### ISSUE TITLE
Support download files via NFS

### ISSUE THREAD

**Issue by PouleR** [Deep-Symmetry/beat-link-trigger#65]
Hi James,

You're doing a great job with all the new features on beat-link and beat-link-trigger, good to see!
Loading and playing tracks is a nice feature! It would also be nice if you can download files from the CDJ's (USB/SD) to your Mac/PC via NFS. Really handy from a FOH when a certain track should be played but not from the CDJ's.

This feature is already available in the Python ProDJ Link tool: https://github.com/flesniak/python-prodj-link, but I think it would be a good thing to add it to this repository.

Keep up the good work!

**Comment by brunchboy** [comment]
Hello, @PouleR thanks for your comment! I am aware that the Python implementation offers this, but I consider that a major problem with that implementation, and I do not plan to offer it myself. If Pioneer starts worrying about people doing that to get copies of music, they are likely to take measures like encrypting their protocol and destroying this entire ecosystem. Similarly, if DJs start worrying about unscrupulous show technicians snagging their “secret weapon” tracks using tools like this, they are going to start unplugging the players from the network before they connect their USBs, making it impossible to use BLT to help run effects.

**Comment by PouleR** [comment]
That makes total sense, I can imagine. Thanks!
