### ISSUE TITLE
Phrase information

### ISSUE THREAD

**Issue by olivernewth** [Deep-Symmetry/beat-link-trigger#73]
Rekordbox can now complete phrase analysis. Is this data available as an output? It would amazing if this is available, as light shows could be automated with ease!

**Comment by brunchboy** [comment]
I have no idea! Please investigate and provide more details. Pull requests are welcome. Have you studied the details of what is currently known, in the [Dysentery](https://github.com/Deep-Symmetry/dysentery) and [Crate Digger](https://github.com/Deep-Symmetry/crate-digger) analysis articles?

**Comment by brunchboy** [comment]
Hmm, scanning the documentation online, it seems this is only available in performance mode, not in export mode, which is what CDJs and software like Beat Link Trigger use. So it is probably not available or relevant to us, unfortunately.

**Comment by brunchboy** [comment]
Perhaps some future hardware from Pioneer will support this in export mode, but until then there is not likely much we can use here. If you have reason to believe otherwise (or anyone has connections with Pioneer that could shed more light on this), I’d be interested in hearing.

**Comment by olivernewth** [comment]
I have looked into this more, and one potential option would be to parse the waveform using a segmentation model, and label these. An example is here:

https://github.com/urinieto/msaf/blob/master/examples/Run%20MSAF.ipynb

Thoughts?

**Comment by brunchboy** [comment]
You could certainly do something like that, it’s well outside the scope of Beat Link Trigger, but I provide all the information you would need to build and use that sort of structure. I’m not sure if you’d be able to use something like jython to run it in-process, but even without that, you could run separate processes, or even build your index structures offline ahead of time and use them from your BLT expressions.

**Comment by brunchboy** [comment]
@olivernewth have you tried running those Python tools you mentioned, and been able to get output that corresponds to the kinds of phrase identification Rekordbox offers? In my own skimming of the documentation, I have been more confused than enlightened… although I did notice that it looks like we should be able to feed in rekordbox’s ideas of where the beats are as an input.

If you can come up with an API I could use to pass an audio file and beat grid to an executable, and get back a list of phrase types with beat number boundaries, then I could  build something that would use that, along with a template mapping phrase type names to cue configurations, to automatically create a show track.

**Comment by brunchboy** [comment]
@mganss has figured out how to find this information in the exported track analysis files, so it looks like we are going to be able to use rekordbox’s analysis from Beat Link Trigger soon. https://github.com/Deep-Symmetry/crate-digger/pull/3 That will require people to purchase performance mode licenses to perform the analysis, though, so if anyone can come up with their own Java implementation that would still be welcome.

**Comment by brunchboy** [comment]
I’m closing this because this information is not exported to USBs or available to CDJs, so there is no way that Beat Link Trigger can use it.
