### ISSUE TITLE
XDJ-RX2 freeze

### ISSUE THREAD

**Issue by cuban8IO** [Deep-Symmetry/beat-link-trigger#74]
### Version of Beat Link Trigger

Current release (Beat-Link-Trigger-0.5.3-Win64.msi)

### Version of Java

.msi package from version 0.5.3

### Version of OS

Windows 10 Professional 64Bit

### The issue you're experiencing

Hi,
I'm new in this thread with Beat link and syncronize to Ableton.
I use PioneerDJ XDJ-RX2 with the Ethernet Link driver on my windows computer. Link works in rekordbox fine. But when i trails to conenct with beat-link-Trigger, the XDJ freezed and nothing to happen on BLT. What do I wrong? 

Thank you very much,
cuban8io

**Comment by brunchboy** [comment]
Unfortunately, as is explained in the [Compatibility](https://github.com/Deep-Symmetry/beat-link-trigger#compatibilityhttps://github.com/Deep-Symmetry/beat-link-trigger#compatibility) section on the project page, the XDJ series of controllers do not, and never have, implemented the DJ Link protocol. They only have Ethernet jacks for loading tracks from Rekordbox. They cannot be used with CDJs or with Beat Link Trigger.
