### ISSUE TITLE
0.6.0 MSI not launching on Windows 10 64

### ISSUE THREAD

**Issue by DJZIPDISKOFFICIAL** [Deep-Symmetry/beat-link-trigger#84]
### Version of Beat Link Trigger

0.6.0

### Version of Java

13.0.1

### Version of OS

Windows 10 Enterprise and Professional 

### The issue you're experiencing

The MSI file installs fine but the application doesn't launch. I've attempted on 2 Windows 10 64 machines with the same results. 0.5.4 worked great.

**Comment by brunchboy** [comment]
Unfortunately I can’t offer Windows installer support. Since it sounds like you have Java 13 installed anyway, please just use the jar file rather than the Windows installer, and try talking on the [Gitter chat room](https://gitter.im/brunchboy/beat-link-trigger) to see if @Kevinnns (who builds the Windows installers) can help you.

**Comment by DJZIPDISKOFFICIAL** [comment]
Thank you!

**Comment by brunchboy** [comment]
I would be interested in hearing what happens when you try to launch the jar file from a command window. (`java -jar beat-link-trigger-0.6.0.jar`).

**Comment by DJZIPDISKOFFICIAL** [comment]
jar file is running fine on the Win10 enterprise machine but no players are handy. I will try the same on the win 10 pro machine this evening.

**Comment by brunchboy** [comment]
Thanks, that is good news anyway!

**Comment by Kevinnns** [comment]
It seems that the previously used JRE isn't enough anymore to run this version of beat-link-trigger. So I've replaced the JRE with the newest Amazon Corretto x64 JDK and created a new MSI and tested that one. @brunchboy You know where to find it and you'd be able to re-upload it.

That does mean that it's a giant MSI once again, which isn't the end of the world, but for the next version I'd like to automatically trim down the JRE/JDK to only what's needed for BLT and add that to the msi once again.

@DJZIPDISKOFFICIAL Thanks for the feedback. Please be patient till @brunchboy uploads the new MSI file and you should be good once again :).

**Comment by brunchboy** [comment]
Thanks so much for jumping on this so quickly, @Kevinnns! I should be able to get a new MSI on the releases page within an hour or so. This is probably why Amazon stopped trying to release a JRE; the notion of a general JRE is no longer supported.

**Comment by brunchboy** [comment]
Ok, I have updated the Release page to contain the new (much larger) MSI. It works in my Windows 10 VM, could you check if it works for you @DJZIPDISKOFFICIAL?

**Comment by brunchboy** [comment]
Have you had a chance to try tis @DJZIPDISKOFFICIAL ? If I don’t hear anything I will close this issue for lack of activity this weekend.

**Comment by brunchboy** [comment]
I’m closing this issue for lack of new information. @Kevinnns had any luck building a custom JRE for BLT? Or should I take another look at how the `javapackager` project is coming along?
