### ISSUE TITLE
Searching for devices window does not close

### ISSUE THREAD

**Issue by drummerclint** [Deep-Symmetry/beat-link-trigger#90]
### Version of Beat Link Trigger

Beat Link Trigger version 0.6.1-SNAPSHOT-80-0x6ed6 built Fri Jan 10 04:25:04 UTC 2020

[blt.log](https://github.com/Deep-Symmetry/beat-link-trigger/files/4044137/blt.log)

### Version of Java

Java version 11.0.5, OpenJDK 64-Bit Server VM, Amazon.com Inc.

### Version of OS

Windows 10

### The issue you're experiencing
![image](https://user-images.githubusercontent.com/19150659/72128913-64c96600-3342-11ea-84c0-43286b54d2e6.png)

Continue offline and quit buttons do not work.  The only way to close the window is to use Task Manager.

While opening the software, I had a previous instance open, in which I closed immediately.

**Comment by brunchboy** [comment]
Thanks for the report! That can’t happen on the Mac, if you try to launch a running application it just comes to the front, so long-term I may want to get smarter about this. Do you know if there is a way to configure Windows applications to work that way? But for now I will at least make this not lock up.

**Comment by brunchboy** [comment]
Thanks so much for finding this @drummerclint! I found a nice way to fix it and give you meaningful error reporting. It turns out that there was a slightly different (but equally bad) way it failed when rekordbox was running, so I fixed that at the same time.

**Comment by brunchboy** [comment]
A new snapshot just built that should fix this. Love that!
